package net.runelite.client.plugins.spoontob.rooms.Nylocas;

import java.util.HashMap;
import net.runelite.api.gameval.NpcID;

enum NylocasType
{
	MELEE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_MELEE, NpcID.TOB_NYLOCAS_FIGHTING_MELEE),
	MELEE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_MELEE, NpcID.TOB_NYLOCAS_BIG_FIGHTING_MELEE),
	RANGE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_RANGED, NpcID.TOB_NYLOCAS_FIGHTING_RANGED),
	RANGE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_RANGED, NpcID.TOB_NYLOCAS_BIG_FIGHTING_RANGED),
	MAGE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_MAGIC, NpcID.TOB_NYLOCAS_FIGHTING_MAGIC),
	MAGE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_MAGIC, NpcID.TOB_NYLOCAS_BIG_FIGHTING_MAGIC),
	SM_MELEE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_MELEE_STORY, NpcID.TOB_NYLOCAS_FIGHTING_MELEE_STORY),
	SM_MELEE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_MELEE_STORY, NpcID.TOB_NYLOCAS_BIG_FIGHTING_MELEE_STORY),
	SM_RANGE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_RANGED_STORY, NpcID.TOB_NYLOCAS_FIGHTING_RANGED_STORY),
	SM_RANGE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_RANGED_STORY, NpcID.TOB_NYLOCAS_BIG_FIGHTING_RANGED_STORY),
	SM_MAGE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_MAGIC_STORY, NpcID.TOB_NYLOCAS_FIGHTING_MAGIC_STORY),
	SM_MAGE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_MAGIC_STORY, NpcID.TOB_NYLOCAS_BIG_FIGHTING_MAGIC_STORY),
	HM_MELEE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_MELEE_HARD, NpcID.TOB_NYLOCAS_FIGHTING_MELEE_HARD),
	HM_MELEE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_MELEE_HARD, NpcID.TOB_NYLOCAS_BIG_FIGHTING_MELEE_HARD),
	HM_RANGE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_RANGED_HARD, NpcID.TOB_NYLOCAS_FIGHTING_RANGED_HARD),
	HM_RANGE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_RANGED_HARD, NpcID.TOB_NYLOCAS_BIG_FIGHTING_RANGED_HARD),
	HM_MAGE_SMALL(NpcID.TOB_NYLOCAS_INCOMING_MAGIC_HARD, NpcID.TOB_NYLOCAS_FIGHTING_MAGIC_HARD),
	HM_MAGE_BIG(NpcID.TOB_NYLOCAS_BIG_INCOMING_MAGIC_HARD, NpcID.TOB_NYLOCAS_BIG_FIGHTING_MAGIC_HARD);

	private static final HashMap<Integer, NylocasType> lookupMap = new HashMap<>();

	static
	{
		for (NylocasType v : values())
		{
			lookupMap.put(v.getId(), v);
			lookupMap.put(v.getAggroId(), v);
		}
	}

	private final int id;
	private final int aggroId;

	NylocasType(int id, int aggroId)
	{
		this.id = id;
		this.aggroId = aggroId;
	}

	public int getId()
	{
		return this.id;
	}

	public int getAggroId()
	{
		return this.aggroId;
	}

	public static HashMap<Integer, NylocasType> getLookupMap()
	{
		return lookupMap;
	}
}
